[program:lopyta-node-1]
command=/var/www/classroom-bringgas/lopyta-server -port 8789 -sync-port 8889 -peer-sync 127.0.0.1:8890 -node node-1
directory=/var/www/classroom-bringgas
autostart=true
autorestart=true
user=yoga
stdout_logfile=/var/log/supervisor/lopyta-node-1-stdout.log
stderr_logfile=/var/log/supervisor/lopyta-node-1-stderr.log
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[program:lopyta-node-2]
command=/var/www/classroom-bringgas/lopyta-server -port 8790 -sync-port 8890 -peer-sync 127.0.0.1:8889 -node node-2
directory=/var/www/classroom-bringgas
autostart=true
autorestart=true
user=yoga
stdout_logfile=/var/log/supervisor/lopyta-node-2-stdout.log
stderr_logfile=/var/log/supervisor/lopyta-node-2-stderr.log
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
